### ISSUE TITLE
Web Compilation Error

### ISSUE THREAD

**Issue by nilotpalkapri** [shawoozy/image_filter_pro#3]
flutter build web --release

Target dart2js failed: ProcessException: Process exited abnormally:
lib/photo_filter.dart:655:36:
Error: Member not found: 'BackgroundIsolateBinaryMessenger.ensureInitialized'.
  BackgroundIsolateBinaryMessenger.ensureInitialized(applyFilterParams.rootIsolateToken);
                                   ^^^^^^^^^^^^^^^^^
/C:/Users/aryad/AppData/Local/Pub/Cache/hosted/pub.dev/image_filter_pro-0.1.10/lib/photo_filter.dart:441:38:
Error: Member not found: 'BackgroundIsolateBinaryMessenger.ensureInitialized'.
    BackgroundIsolateBinaryMessenger.ensureInitialized(applyFilterParams.rootIsolateToken);
                                     ^^^^^^^^^^^^^^^^^
/C:/Users/aryad/AppData/Local/Pub/Cache/hosted/pub.dev/cross_file-0.3.3+8/lib/src/types/html.dart:136:42:
Warning: Operand of null-aware operation '!' has type 'int' which excludes null.
    if (isSafari() && _length != null && _length! >= _fourGigabytes) {
                                         ^
Error: Compilation failed.
  Command: E:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev E:\flutter\bin\cache\dart-sdk\bin\snapshots\dart2js.dart.snapshot
  --platform-binaries=E:\flutter\bin\cache\flutter_web_sdk\kernel --invoker=flutter_tool -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/6e2ea58a5ccbefcfadc2d4b7b8045fc6c20ab812/ --native-null-assertions --no-source-maps -o
  E:\Nilotpal\Projects\Flutter_Apps\scand\.dart_tool\flutter_build\b6d5346a80891bd891a3a9b24bb5abc7\app.dill --packages=.dart_tool/package_config.json --cfe-only
  E:\Nilotpal\Projects\Flutter_Apps\scand\.dart_tool\flutter_build\b6d5346a80891bd891a3a9b24bb5abc7\main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:127:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:280:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:189:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:89:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:199:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

Compiling lib\main.dart for the Web...                              9.0s
Exception: Failed to compile application for the Web.

See the below article for solution
https://dart.dev/guides/libraries/create-packages#conditionally-importing-and-exporting-library-files

**Comment by shawoozy** [comment]
I have not tested it on Web... if you found a solution please create a PR @nilotpalkapri
